"""One structured-event pipeline for every ``worker.*`` module.

Console logging stays human-readable and unchanged. This module adds a second,
machine-readable sink: newline-delimited JSON, one object per event, routed
through ordinary Python logging so a module only has to call :func:`emit`.

Design constraints that shaped it:

  * **Metadata only.** Raw JSON, HTML, cookies, tokens, API keys, full query
    URLs and authorization values never enter an event. Bodies live in the
    artifact store (:mod:`worker.core.scrape_artifacts`) and events carry only
    an ``artifact_id`` + digest.
  * **Never fails a report.** Every path here is wrapped; a broken sink degrades
    to silence, not to an exception inside the scraper.
  * **Installed at most once.** Handlers are tagged, mirroring the console/file
    handler discipline in ``worker/main.py``, so a re-import cannot double every
    event.
"""

from __future__ import annotations

import json
import logging
import logging.handlers
import os
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Optional
from urllib.parse import urlparse

from worker.core import scrape_trace

# Bumped when the meaning of an existing field changes, so a consumer reading
# old and new lines together can tell them apart.
EVENT_SCHEMA_VERSION = 1

# The attribute an event dict rides on. Records without it are ordinary console
# logs and are dropped by the JSONL handler's filter.
EVENT_ATTR = "scrape_event"

_HANDLER_TAG = "_airahost_event_handler"
_events_logger = logging.getLogger("worker.events")

# ── Event names ──────────────────────────────────────────────────────────────
# Stable strings: operators grep these, so they are treated as API.
DIRECT_HTTP_STARTED = "direct_http_started"
DIRECT_HTTP_SUCCEEDED = "direct_http_succeeded"
DIRECT_HTTP_DEGRADED = "direct_http_degraded"
DIRECT_HTTP_BLOCKED = "direct_http_blocked"
DIRECT_HTTP_OVERLOADED = "direct_http_overloaded"

RAW_HTML_FETCH_STARTED = "raw_http_html_started"
RAW_HTML_FETCH_SUCCEEDED = "raw_http_html_succeeded"
RAW_HTML_FETCH_FAILED = "raw_http_html_failed"

PLAYWRIGHT_STARTED = "playwright_started"
PLAYWRIGHT_CAPTURED_JSON = "playwright_captured_json"
PLAYWRIGHT_FAILED = "playwright_failed"

FALLBACK_SELECTED = "fallback_selected"
COOLDOWN_STARTED = "cooldown_started"
CIRCUIT_OPENED = "circuit_opened"
CIRCUIT_HALF_OPEN = "circuit_half_open"
CIRCUIT_CLOSED = "circuit_closed"
LIMIT_ADJUSTED = "limit_adjusted"
RETRY_SCHEDULED = "retry_scheduled"
RETRY_BUDGET_EXHAUSTED = "retry_budget_exhausted"
ARTIFACT_CAPTURED = "artifact_captured"
ARTIFACT_CAPTURE_FAILED = "artifact_capture_failed"
ADMISSION_CONFIGURED = "admission_configured"
CALIBRATION_EVENT = "calibration_event"

# ── Redaction ────────────────────────────────────────────────────────────────
# Applied to every string value in an event as a last line of defence. The real
# protection is that callers pass metadata, not bodies; this catches mistakes.
_SECRET_KEY_RE = re.compile(
    r"(cookie|set-cookie|authorization|auth|token|secret|password|passwd|api[_-]?key"
    r"|apikey|session|bearer|signature|sig|credential)",
    re.IGNORECASE,
)
_BEARER_RE = re.compile(r"\bBearer\s+[A-Za-z0-9._~+/=-]{8,}", re.IGNORECASE)
_LONG_TOKEN_RE = re.compile(r"\b[A-Za-z0-9_-]{40,}\b")
REDACTED = "[redacted]"

# Bounds on any single event so a stray large value cannot bloat the log file.
MAX_STRING_LEN = 512
MAX_FIELDS = 60


def sanitize_endpoint(url: Any) -> Dict[str, Optional[str]]:
    """Host + path only. The query string carries location, dates and tokens."""
    try:
        parsed = urlparse(str(url or ""))
    except Exception:
        return {"endpoint_host": None, "endpoint_path": None}
    path = parsed.path or None
    if path:
        # Persisted-query hashes appear as a path segment; keep the operation
        # name, drop the 64-hex hash so the path stays low-cardinality.
        path = re.sub(r"/[0-9a-f]{32,}(?=/|$)", "/<hash>", path)
    return {"endpoint_host": parsed.netloc or None, "endpoint_path": path}


# Fields whose values are generated by this pipeline and are meaningless to an
# attacker but essential to an operator. Exempt from the long-token heuristic,
# which would otherwise redact an artifact's SHA-256 — the one field that lets
# someone verify they are reading the payload the event refers to.
_SAFE_IDENTIFIER_KEYS = frozenset(
    {
        "artifact_sha256",
        "artifact_id",
        "artifact_path",
        "trace_id",
        "search_id",
        "attempt_id",
        "worker_instance_id",
    }
)


def _scrub_value(key: str, value: Any) -> Any:
    if isinstance(value, str):
        if key in _SAFE_IDENTIFIER_KEYS:
            return value[:MAX_STRING_LEN]
        if _SECRET_KEY_RE.search(str(key)):
            return REDACTED
        scrubbed = _BEARER_RE.sub(REDACTED, value)
        scrubbed = _LONG_TOKEN_RE.sub(REDACTED, scrubbed)
        if len(scrubbed) > MAX_STRING_LEN:
            scrubbed = scrubbed[:MAX_STRING_LEN] + "…"
        return scrubbed
    if isinstance(value, dict):
        return {str(k): _scrub_value(str(k), v) for k, v in list(value.items())[:MAX_FIELDS]}
    if isinstance(value, (list, tuple)):
        return [_scrub_value(key, v) for v in list(value)[:MAX_FIELDS]]
    if isinstance(value, (int, float, bool)) or value is None:
        return value
    return _scrub_value(key, str(value))


def build_event(event: str, fields: Dict[str, Any]) -> Dict[str, Any]:
    """Assemble one event dict: timestamp, schema, trace context, scrubbed fields."""
    payload: Dict[str, Any] = {
        "ts": datetime.now(timezone.utc).isoformat(timespec="milliseconds").replace("+00:00", "Z"),
        "schema_version": EVENT_SCHEMA_VERSION,
        "event": str(event),
    }
    try:
        payload.update(scrape_trace.context_fields())
    except Exception:
        pass
    for key, value in list(fields.items())[:MAX_FIELDS]:
        if value is None:
            continue
        payload[str(key)] = _scrub_value(str(key), value)
    return payload


def emit(event: str, *, level: int = logging.INFO, **fields: Any) -> None:
    """Emit one structured event. Never raises."""
    try:
        payload = build_event(event, fields)
        summary = " ".join(
            f"{k}={v}"
            for k, v in payload.items()
            if k not in ("ts", "schema_version") and v is not None
        )
        _events_logger.log(level, "%s", summary, extra={EVENT_ATTR: payload})
    except Exception:  # pragma: no cover - defensive; logging must never fail a report
        pass


# ── JSONL sink ───────────────────────────────────────────────────────────────


class JsonlEventFormatter(logging.Formatter):
    """Serialize the record's event dict as one JSON line."""

    def format(self, record: logging.LogRecord) -> str:
        payload = getattr(record, EVENT_ATTR, None)
        if not isinstance(payload, dict):
            payload = {"event": "log_record", "message": record.getMessage()}
        line = dict(payload)
        line.setdefault("severity", record.levelname)
        line.setdefault("logger", record.name)
        try:
            return json.dumps(line, ensure_ascii=False, default=str)
        except Exception:
            return json.dumps({"event": "event_serialization_failed", "logger": record.name})


class _EventOnlyFilter(logging.Filter):
    def filter(self, record: logging.LogRecord) -> bool:
        return isinstance(getattr(record, EVENT_ATTR, None), dict)


class _WindowsSafeRotatingFileHandler(logging.handlers.RotatingFileHandler):
    """Skip a rollover Windows refuses (WinError 32) rather than drop the record.

    Same race as ``worker/main.py``'s log handler: another handle on the file
    (antivirus, indexer, a tail) makes ``os.rename`` fail on Windows only.
    """

    def doRollover(self) -> None:
        try:
            super().doRollover()
        except (PermissionError, OSError):
            pass


def _env_flag(name: str, default: bool = False) -> bool:
    raw = str(os.getenv(name, "") or "").strip().lower()
    if not raw:
        return default
    return raw in ("1", "true", "yes", "on")


def _env_int(name: str, default: int) -> int:
    try:
        return int(str(os.getenv(name, "") or "").strip() or default)
    except Exception:
        return default


def default_jsonl_path() -> Path:
    configured = str(os.getenv("WORKER_EVENT_LOG_PATH", "") or "").strip()
    if configured:
        return Path(configured)
    return Path(__file__).resolve().parent.parent / "logs" / "worker.jsonl"


def install_event_sink(force: bool = False) -> Optional[logging.Handler]:
    """Attach the JSONL sink to the ``worker.events`` logger.

    Idempotent: a tagged handler is installed at most once, so a second import
    of the worker entrypoint cannot write every event twice. Returns the
    handler, or None when disabled or when installation failed (a missing event
    log must not stop the worker from starting).

    ``WORKER_EVENT_LOG_STDOUT=1`` emits the same JSON to stdout instead of a
    file — the transport an external log platform's agent expects. No hosted
    vendor is contacted in either mode.
    """
    if not _env_flag("WORKER_EVENT_LOG_ENABLED", True):
        return None
    existing = [h for h in _events_logger.handlers if hasattr(h, _HANDLER_TAG)]
    if existing and not force:
        return existing[0]
    for handler in existing:
        _events_logger.removeHandler(handler)

    handler: logging.Handler
    kind: str
    try:
        if _env_flag("WORKER_EVENT_LOG_STDOUT", False):
            import sys

            handler = logging.StreamHandler(sys.stdout)
            kind = "stdout"
        else:
            path = default_jsonl_path()
            path.parent.mkdir(parents=True, exist_ok=True)
            handler = _WindowsSafeRotatingFileHandler(
                filename=str(path),
                maxBytes=_env_int("WORKER_EVENT_LOG_MAX_BYTES", 20 * 1024 * 1024),
                backupCount=_env_int("WORKER_EVENT_LOG_BACKUPS", 5),
                encoding="utf-8",
            )
            kind = "jsonl"
    except Exception:
        return None

    handler.setFormatter(JsonlEventFormatter())
    handler.addFilter(_EventOnlyFilter())
    setattr(handler, _HANDLER_TAG, kind)
    _events_logger.addHandler(handler)
    _events_logger.setLevel(logging.INFO)
    # Events also reach the console through the root handlers as a readable
    # summary line; propagate stays on deliberately.
    return handler


def uninstall_event_sink() -> None:
    """Remove the JSONL sink. Used by tests to isolate handler state."""
    for handler in [h for h in _events_logger.handlers if hasattr(h, _HANDLER_TAG)]:
        _events_logger.removeHandler(handler)
        try:
            handler.close()
        except Exception:
            pass
