from __future__ import annotations

import argparse
import os
import pprint
from pathlib import Path
from typing import Any, Dict, Optional
from urllib.parse import quote, urlencode

from playwright.sync_api import sync_playwright


def _dump_python_module(payload: Dict[str, Any], out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    # Emit a Python literal (True/False/None), not JSON (true/false/null), so the
    # generated module is importable — matching stayspdp_template.py's style.
    body = pprint.pformat(payload, indent=1, width=100, sort_dicts=False)
    module = (
        "# Auto-generated by worker/record_stayssearch_template.py\n"
        "# Do not edit manually.\n\n"
        "HARDCODED_STAYS_SEARCH_TEMPLATE = "
        f"{body}\n"
    )
    out_path.write_text(module, encoding="utf-8")


def _build_search_url(query: str, checkin: str, checkout: str, adults: int) -> str:
    path_query = query.replace(", ", ",").replace(",", "--")
    params = {
        "refinement_paths[]": "/homes",
        "checkin": checkin,
        "checkout": checkout,
        "adults": adults,
        "query": query,
        "search_type": "AUTOSUGGEST",
        "currency": "USD",
        "locale": "en-CA",
    }
    return f"https://www.airbnb.com/s/{quote(path_query)}/homes?{urlencode(params)}"


def _try_trigger(page) -> Optional[str]:
    """
    Force Airbnb's client-side StaysSearch XHR via a real in-page interaction.
    The first results page is server-rendered, so only pagination / map moves /
    filter changes issue the GraphQL StaysSearch POST. Returns the trigger used.
    """
    # 1) Pagination "Next" — the most reliable trigger when results span pages.
    for sel in (
        'a[aria-label="Next"]',
        'a[aria-label="Next page"]',
        'nav[aria-label*="Search results pages"] a[aria-label="Next"]',
    ):
        try:
            el = page.query_selector(sel)
            if el and el.is_visible():
                el.scroll_into_view_if_needed(timeout=2000)
                el.click(timeout=3000)
                return f"pagination:{sel}"
        except Exception:
            pass

    # 2) Map zoom-in — pans/zooms the viewport, firing a map StaysSearch.
    for sel in ('button[aria-label="Zoom in"]', 'button[aria-label="Zoom in map"]'):
        try:
            el = page.query_selector(sel)
            if el and el.is_visible():
                el.click(timeout=3000)
                return f"zoom:{sel}"
        except Exception:
            pass

    # 3) Drag the map — last-resort viewport change.
    for sel in (
        '[data-testid="map/GoogleMap"]',
        'div[aria-roledescription="map"]',
        '[aria-label="Map"]',
    ):
        try:
            map_el = page.query_selector(sel)
            if not map_el:
                continue
            box = map_el.bounding_box()
            if not box:
                continue
            cx, cy = box["x"] + box["width"] / 2, box["y"] + box["height"] / 2
            page.mouse.move(cx, cy)
            page.mouse.down()
            page.mouse.move(cx - 160, cy - 110, steps=12)
            page.mouse.up()
            return f"map_drag:{sel}"
        except Exception:
            pass
    return None


def capture_stays_search_template(
    search_url: str,
    cdp_url: str,
    timeout_ms: int = 30000,
) -> Dict[str, Any]:
    """
    Capture a live StaysSearch POST request as a replayable template by attaching
    to an existing logged-in Chrome over CDP and driving an in-page interaction
    (pagination / map move) that forces the client-side StaysSearch XHR.
    """
    captured: Optional[Dict[str, Any]] = None
    seen_api: list[str] = []

    def on_request(request) -> None:
        nonlocal captured
        url = request.url
        if "/api/v3/" in url:
            marker = f"{request.method} {url.split('?', 1)[0]}"
            if marker not in seen_api:
                seen_api.append(marker)
        if captured is not None or request.method != "POST":
            return
        if "/api/v3/StaysSearch" not in url:
            return
        try:
            captured = {
                "url": url,
                "headers": request.headers,
                "post_data": request.post_data_json,
            }
        except Exception:
            captured = None

    with sync_playwright() as p:
        browser = p.chromium.connect_over_cdp(cdp_url, timeout=15000)
        print(f"Connected to existing browser over CDP: {cdp_url}")
        if not browser.contexts:
            raise RuntimeError("CDP browser has no contexts; open a normal Chrome window first.")
        context = browser.contexts[0]
        page = context.new_page()
        page.on("request", on_request)
        try:
            page.goto(search_url, wait_until="domcontentloaded", timeout=timeout_ms)
            try:
                page.wait_for_load_state("networkidle", timeout=10000)
            except Exception:
                pass
            page.wait_for_timeout(1500)

            for attempt in range(12):
                if captured is not None:
                    break
                page.mouse.wheel(0, 2400)
                page.wait_for_timeout(500)
                trigger = _try_trigger(page)
                if trigger:
                    print(f"Triggered search interaction: {trigger}")
                # Give the XHR time to fire before the next attempt.
                for _ in range(8):
                    if captured is not None:
                        break
                    page.wait_for_timeout(500)
        finally:
            # Only close our own tab — never the user's CDP browser.
            try:
                page.close()
            except Exception:
                pass

    if captured is None:
        raise RuntimeError(
            "Timed out waiting for StaysSearch capture. "
            f"API requests seen: {seen_api or 'none'}. "
            "Ensure the search has multiple result pages (try a busy city) and "
            "that Chrome is logged into Airbnb."
        )
    return captured


def main() -> None:
    parser = argparse.ArgumentParser(description="Capture and hardcode a StaysSearch template.")
    parser.add_argument("--query", required=True, help='Search location, e.g. "Austin, Texas".')
    parser.add_argument("--checkin", required=True, help="Check-in date YYYY-MM-DD.")
    parser.add_argument("--checkout", required=True, help="Check-out date YYYY-MM-DD.")
    parser.add_argument("--adults", type=int, default=1, help="Adults count for the search.")
    parser.add_argument(
        "--out",
        default="worker/scraper/stayssearch_template.py",
        help="Output Python module path.",
    )
    parser.add_argument(
        "--cdp-url",
        default=os.getenv("CDP_URL", "http://127.0.0.1:9222"),
        help="CDP endpoint of an existing logged-in Chrome (default: 127.0.0.1:9222).",
    )
    parser.add_argument(
        "--timeout-ms",
        type=int,
        default=30000,
        help="Per-navigation timeout in milliseconds.",
    )
    args = parser.parse_args()

    search_url = _build_search_url(args.query, args.checkin, args.checkout, args.adults)
    payload = capture_stays_search_template(
        search_url, cdp_url=args.cdp_url, timeout_ms=args.timeout_ms
    )
    out_path = Path(args.out)
    _dump_python_module(payload, out_path)
    print(f"Wrote hardcoded StaysSearch template to: {out_path}")


if __name__ == "__main__":
    main()
